version: "3"
services:

  app:
    depends_on:
      - mongo
    container_name: dockerize-node-mongo-app
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - HOST=$HOST
      - PORT=$PORT
    #map from image port (3000) to actual container port
    ports:
      - "8080:$PORT"
    links:
      - mongo

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE=your-database-name
      MONGO_INITDB_ROOT_USERNAME=my-container-root-username
      MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "$DB_PORT:$DB_PORT"

    #override mongo-init.js & persist data
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro