version: "2"
services:
 back:
  container_name: back
  restart: always
  build: .
  ports:
   - "3000:3000"
  depends_on:
   - mongo
  volumes:
   - res:/user/src/app/res
 mongo:
  container_name: mongo
  image: mongo
  ports:
   - "27017:27017"
  volumes:
   - data-volume:/data/db
volumes:
 res:
 data-volume:
